import type { Doctor } from "./types";

export const initialDoctors: Doctor[] = [
  {
    id: 1,
    stt: 1,
    fullName: "BS. Nguyễn Văn Bình",
    avatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
    specialty: "Tim mạch",
    qualifications: "MD, PhD - Trưởng khoa",
    experience: "12 năm",
    email: "dr.binh@clinic.com",
    clinicRoom: "P01",
    status: "Đang hoạt động",
    ratingAverage: 4.9,
    totalReviews: 156,
  },
  {
    id: 2,
    stt: 2,
    fullName: "BS. Trần Thị Lan",
    avatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
    specialty: "Thần kinh học",
    qualifications: "MD - Phó khoa",
    experience: "8 năm",
    email: "dr.lan@clinic.com",
    clinicRoom: "P02",
    status: "Đang hoạt động",
    ratingAverage: 4.7,
    totalReviews: 98,
  },
  {
    id: 3,
    stt: 3,
    fullName: "BS. Lê Văn Phúc",
    avatar: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
    specialty: "Nội khoa",
    qualifications: "MD, FCPS",
    experience: "15 năm",
    email: "dr.phuc@clinic.com",
    clinicRoom: "P03",
    status: "Nghỉ phép",
    ratingAverage: 4.8,
    totalReviews: 210,
    leaveStartDate: "28/07/2026",
    leaveEndDate: "05/08/2026",
    leaveReason: "Tham gia hội thảo Y khoa quốc tế tại Hà Nội",
    leaveStatus: "Đã duyệt",
  },
  {
    id: 4,
    stt: 4,
    fullName: "BS. Hoàng Minh Tuấn",
    avatar: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
    specialty: "Da liễu",
    qualifications: "Bác sĩ CKI",
    experience: "6 năm",
    email: "dr.tuan@clinic.com",
    clinicRoom: "P04",
    status: "Ngưng hoạt động",
    ratingAverage: 4.5,
    totalReviews: 42,
  },
  {
    id: 5,
    stt: 5,
    fullName: "BS. Phạm Thanh Thảo",
    avatar: "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=300&auto=format&fit=crop&q=80",
    specialty: "Nhi khoa",
    qualifications: "Thạc sĩ Y khoa",
    experience: "10 năm",
    email: "dr.thao@clinic.com",
    clinicRoom: "P05",
    status: "Đã khóa",
    ratingAverage: 4.2,
    totalReviews: 18,
  },
  {
    id: 6,
    stt: 6,
    fullName: "BS. Võ Quốc Bảo",
    avatar: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=300&auto=format&fit=crop&q=80",
    specialty: "Chấn thương chỉnh hình",
    qualifications: "Bác sĩ CKII",
    experience: "14 năm",
    email: "dr.bao@clinic.com",
    clinicRoom: "P06",
    status: "Nghỉ phép",
    ratingAverage: 4.6,
    totalReviews: 64,
    leaveStartDate: "01/08/2026",
    leaveEndDate: "03/08/2026",
    leaveReason: "Nghỉ phép cá nhân giải quyết việc gia đình",
    leaveStatus: "Chờ duyệt",
  },
  {
    id: 7,
    stt: 7,
    fullName: "BS. Đặng Mai Phương",
    avatar: "https://images.unsplash.com/photo-1594824813566-88855376170d?w=300&auto=format&fit=crop&q=80",
    specialty: "Phụ khoa",
    qualifications: "Bác sĩ CKI",
    experience: "7 năm",
    email: "dr.phuong@clinic.com",
    clinicRoom: "P07",
    status: "Nghỉ phép",
    ratingAverage: 4.7,
    totalReviews: 85,
    leaveStartDate: "20/07/2026",
    leaveEndDate: "25/07/2026",
    leaveReason: "Xin nghỉ phép việc gia đình trùng lịch trực cấp cứu bệnh viện",
    leaveStatus: "Từ chối",
  },
  {
    id: 8,
    stt: 8,
    fullName: "BS. Bùi Anh Tuấn",
    avatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
    specialty: "Tai Mũi Họng",
    qualifications: "Thạc sĩ Bác sĩ",
    experience: "9 năm",
    email: "dr.anhtuan@clinic.com",
    clinicRoom: "P08",
    status: "Nghỉ phép",
    ratingAverage: 4.8,
    totalReviews: 112,
    leaveStartDate: "10/08/2026",
    leaveEndDate: "12/08/2026",
    leaveReason: "Thay đổi kế hoạch công tác cá nhân nên hủy đơn xin nghỉ",
    leaveStatus: "Đã hủy",
  },
];
