import type { Specialty } from "./types";

export const initialSpecialties: Specialty[] = [
  {
    id: 1,
    stt: 1,
    name: "Nội khoa",
    description: "Chẩn đoán và điều trị các bệnh nội khoa",
    doctorCount: 3,
    status: "Đang hoạt động",
  },
  {
    id: 2,
    stt: 2,
    name: "Tim mạch",
    description: "Các bệnh về tim và mạch máu",
    doctorCount: 2,
    status: "Đang hoạt động",
  },
  {
    id: 3,
    stt: 3,
    name: "Thần kinh học",
    description: "Các rối loạn của hệ thần kinh",
    doctorCount: 1,
    status: "Đang hoạt động",
  },
  {
    id: 4,
    stt: 4,
    name: "Da liễu",
    description: "Các bệnh về da, tóc và móng",
    doctorCount: 2,
    status: "Đang hoạt động",
  },
  {
    id: 5,
    stt: 5,
    name: "Chỉnh hình",
    description: "Các bệnh lý về cơ xương khớp",
    doctorCount: 2,
    status: "Đang hoạt động",
  },
  {
    id: 6,
    stt: 6,
    name: "Phụ khoa",
    description: "Sức khỏe sinh sản phụ nữ",
    doctorCount: 3,
    status: "Đang hoạt động",
  },
  {
    id: 7,
    stt: 7,
    name: "Nhãn khoa",
    description: "Chăm sóc mắt và thị lực",
    doctorCount: 1,
    status: "Đang hoạt động",
  },
  {
    id: 8,
    stt: 8,
    name: "Tai mũi họng",
    description: "Các bệnh lý về tai, mũi và họng",
    doctorCount: 1,
    status: "Đang hoạt động",
  },
  {
    id: 9,
    stt: 9,
    name: "Nhi khoa",
    description: "Chăm sóc y tế cho trẻ sơ sinh và trẻ nhỏ",
    doctorCount: 2,
    status: "Đang hoạt động",
  },
  {
    id: 10,
    stt: 10,
    name: "Ung thư",
    description: "Chẩn đoán và điều trị ung thư",
    doctorCount: 10,
    status: "Đang hoạt động",
  },
];
