import type { WorkSchedule } from "./types";

export const initialWorkSchedules: WorkSchedule[] = [
  {
    scheduleId: 1,
    scheduleCode: "1",
    doctorId: 1,
    doctorName: "BS. Nguyễn Văn Bình",
    specialty: "Tim mạch",
    workDate: "31/07/2026",
    startTime: "08:00",
    endTime: "12:00",
    status: "Còn lịch để đặt",
    timeSlots: [
      {
        slotId: 101,
        slotCode: "1",
        scheduleCode: "1",
        slotOrder: 1,
        startTime: "08:00",
        endTime: "08:30",
        status: "Đã đặt lịch",
        patientName: "Nguyễn Văn An",
      },
      {
        slotId: 102,
        slotCode: "2",
        scheduleCode: "1",
        slotOrder: 2,
        startTime: "08:30",
        endTime: "09:00",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 103,
        slotCode: "3",
        scheduleCode: "1",
        slotOrder: 3,
        startTime: "09:00",
        endTime: "09:30",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 104,
        slotCode: "4",
        scheduleCode: "1",
        slotOrder: 4,
        startTime: "09:30",
        endTime: "10:00",
        status: "Đã đặt lịch",
        patientName: "Phạm Thị Dung",
      },
      {
        slotId: 105,
        slotCode: "5",
        scheduleCode: "1",
        slotOrder: 5,
        startTime: "10:00",
        endTime: "10:30",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 106,
        slotCode: "6",
        scheduleCode: "1",
        slotOrder: 6,
        startTime: "10:30",
        endTime: "11:00",
        status: "Đã đóng",
      },
      {
        slotId: 107,
        slotCode: "7",
        scheduleCode: "1",
        slotOrder: 7,
        startTime: "11:00",
        endTime: "11:30",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 108,
        slotCode: "8",
        scheduleCode: "1",
        slotOrder: 8,
        startTime: "11:30",
        endTime: "12:00",
        status: "Chưa đặt lịch",
      },
    ],
  },
  {
    scheduleId: 2,
    scheduleCode: "2",
    doctorId: 2,
    doctorName: "BS. Trần Thị Lan",
    specialty: "Thần kinh học",
    workDate: "31/07/2026",
    startTime: "13:30",
    endTime: "17:00",
    status: "Đã hết lịch để đặt",
    timeSlots: [
      {
        slotId: 201,
        slotCode: "1",
        scheduleCode: "2",
        slotOrder: 1,
        startTime: "13:30",
        endTime: "14:00",
        status: "Đã đặt lịch",
        patientName: "Trần Thị Bình",
      },
      {
        slotId: 202,
        slotCode: "2",
        scheduleCode: "2",
        slotOrder: 2,
        startTime: "14:00",
        endTime: "14:30",
        status: "Đã đặt lịch",
        patientName: "Lê Minh Cường",
      },
      {
        slotId: 203,
        slotCode: "3",
        scheduleCode: "2",
        slotOrder: 3,
        startTime: "14:30",
        endTime: "15:00",
        status: "Đã đặt lịch",
        patientName: "Hoàng Văn Em",
      },
      {
        slotId: 204,
        slotCode: "4",
        scheduleCode: "2",
        slotOrder: 4,
        startTime: "15:00",
        endTime: "15:30",
        status: "Đã đặt lịch",
        patientName: "Võ Thị Giang",
      },
      {
        slotId: 205,
        slotCode: "5",
        scheduleCode: "2",
        slotOrder: 5,
        startTime: "15:30",
        endTime: "16:00",
        status: "Đã đặt lịch",
        patientName: "Nguyễn Thị Hoa",
      },
      {
        slotId: 206,
        slotCode: "6",
        scheduleCode: "2",
        slotOrder: 6,
        startTime: "16:00",
        endTime: "16:30",
        status: "Đã đặt lịch",
        patientName: "Đặng Văn Kiên",
      },
      {
        slotId: 207,
        slotCode: "7",
        scheduleCode: "2",
        slotOrder: 7,
        startTime: "16:30",
        endTime: "17:00",
        status: "Đã đặt lịch",
        patientName: "Bùi Thị Mai",
      },
    ],
  },
  {
    scheduleId: 3,
    scheduleCode: "3",
    doctorId: 3,
    doctorName: "BS. Lê Văn Phúc",
    specialty: "Nội khoa",
    workDate: "01/08/2026",
    startTime: "08:00",
    endTime: "11:30",
    status: "Không hoạt động",
    timeSlots: [
      {
        slotId: 301,
        slotCode: "1",
        scheduleCode: "3",
        slotOrder: 1,
        startTime: "08:00",
        endTime: "08:30",
        status: "Đã đóng",
      },
      {
        slotId: 302,
        slotCode: "2",
        scheduleCode: "3",
        slotOrder: 2,
        startTime: "08:30",
        endTime: "09:00",
        status: "Đã đóng",
      },
      {
        slotId: 303,
        slotCode: "3",
        scheduleCode: "3",
        slotOrder: 3,
        startTime: "09:00",
        endTime: "09:30",
        status: "Đã đóng",
      },
      {
        slotId: 304,
        slotCode: "4",
        scheduleCode: "3",
        slotOrder: 4,
        startTime: "09:30",
        endTime: "10:00",
        status: "Đã đóng",
      },
      {
        slotId: 305,
        slotCode: "5",
        scheduleCode: "3",
        slotOrder: 5,
        startTime: "10:00",
        endTime: "10:30",
        status: "Đã đóng",
      },
      {
        slotId: 306,
        slotCode: "6",
        scheduleCode: "3",
        slotOrder: 6,
        startTime: "10:30",
        endTime: "11:00",
        status: "Đã đóng",
      },
      {
        slotId: 307,
        slotCode: "7",
        scheduleCode: "3",
        slotOrder: 7,
        startTime: "11:00",
        endTime: "11:30",
        status: "Đã đóng",
      },
    ],
  },
  {
    scheduleId: 4,
    scheduleCode: "4",
    doctorId: 4,
    doctorName: "BS. Hoàng Minh Tuấn",
    specialty: "Da liễu",
    workDate: "01/08/2026",
    startTime: "08:00",
    endTime: "12:00",
    status: "Trống lịch",
    timeSlots: [
      {
        slotId: 401,
        slotCode: "1",
        scheduleCode: "4",
        slotOrder: 1,
        startTime: "08:00",
        endTime: "08:30",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 402,
        slotCode: "2",
        scheduleCode: "4",
        slotOrder: 2,
        startTime: "08:30",
        endTime: "09:00",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 403,
        slotCode: "3",
        scheduleCode: "4",
        slotOrder: 3,
        startTime: "09:00",
        endTime: "09:30",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 404,
        slotCode: "4",
        scheduleCode: "4",
        slotOrder: 4,
        startTime: "09:30",
        endTime: "10:00",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 405,
        slotCode: "5",
        scheduleCode: "4",
        slotOrder: 5,
        startTime: "10:00",
        endTime: "10:30",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 406,
        slotCode: "6",
        scheduleCode: "4",
        slotOrder: 6,
        startTime: "10:30",
        endTime: "11:00",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 407,
        slotCode: "7",
        scheduleCode: "4",
        slotOrder: 7,
        startTime: "11:00",
        endTime: "11:30",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 408,
        slotCode: "8",
        scheduleCode: "4",
        slotOrder: 8,
        startTime: "11:30",
        endTime: "12:00",
        status: "Chưa đặt lịch",
      },
    ],
  },,
  {
    scheduleId: 5,
    scheduleCode: "5",
    doctorId: 5,
    doctorName: "BS. Phạm Thanh Thảo",
    specialty: "Nhi khoa",
    workDate: "02/08/2026",
    startTime: "14:00",
    endTime: "18:00",
    status: "Trống lịch",
    timeSlots: [
      {
        slotId: 501,
        slotCode: "1",
        scheduleCode: "5",
        slotOrder: 1,
        startTime: "14:00",
        endTime: "14:30",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 502,
        slotCode: "2",
        scheduleCode: "5",
        slotOrder: 2,
        startTime: "14:30",
        endTime: "15:00",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 503,
        slotCode: "3",
        scheduleCode: "5",
        slotOrder: 3,
        startTime: "15:00",
        endTime: "15:30",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 504,
        slotCode: "4",
        scheduleCode: "5",
        slotOrder: 4,
        startTime: "15:30",
        endTime: "16:00",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 505,
        slotCode: "5",
        scheduleCode: "5",
        slotOrder: 5,
        startTime: "16:00",
        endTime: "16:30",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 506,
        slotCode: "6",
        scheduleCode: "5",
        slotOrder: 6,
        startTime: "16:30",
        endTime: "17:00",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 507,
        slotCode: "7",
        scheduleCode: "5",
        slotOrder: 7,
        startTime: "17:00",
        endTime: "17:30",
        status: "Chưa đặt lịch",
      },
      {
        slotId: 508,
        slotCode: "8",
        scheduleCode: "5",
        slotOrder: 8,
        startTime: "17:30",
        endTime: "18:00",
        status: "Chưa đặt lịch",
      },
    ],
  },
];

export const doctorsList = [
  "BS. Nguyễn Văn Bình",
  "BS. Trần Thị Lan",
  "BS. Lê Văn Phúc",
  "BS. Hoàng Minh Tuấn",
  "BS. Phạm Thanh Thảo",
  "BS. Ngô Đức Anh",
  "BS. Vũ Thị Hồng",
];
