import type { Appointment } from "./types";

export const initialAppointments: Appointment[] = [
  {
    id: 1,
    patientName: "Nguyễn Văn An",
    doctorName: "BS. Trần Minh Tuấn",
    appointmentDate: "01/08/2026",
    appointmentTime: "08:00 - 08:30",
    reason: "Khám sức khỏe tổng quát",
    queueNumber: 1,
    status: "Scheduled",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Đã đặt lịch khám qua ứng dụng",
  },
  {
    id: 2,
    patientName: "Lê Thị Hoa",
    doctorName: "BS. Trần Minh Tuấn",
    appointmentDate: "01/08/2026",
    appointmentTime: "08:30 - 09:00",
    reason: "Đau đầu kéo dài",
    queueNumber: 2,
    status: "Scheduled",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Đã đặt lịch",
  },
  {
    id: 3,
    patientName: "Phạm Văn Nam",
    doctorName: "BS. Nguyễn Công Toại",
    appointmentDate: "01/08/2026",
    appointmentTime: "13:00 - 13:30",
    reason: "Khám đau dạ dày",
    queueNumber: 1,
    status: "Scheduled",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Chờ đến ngày khám",
  },
  {
    id: 4,
    patientName: "Trần Thị Mai",
    doctorName: "BS. Trần Minh Tuấn",
    appointmentDate: "01/08/2026",
    appointmentTime: "09:00 - 09:30",
    reason: "Sốt và ho",
    queueNumber: 3,
    status: "Waiting",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Đã check-in, đang chờ khám",
  },
  {
    id: 5,
    patientName: "Võ Minh Đức",
    doctorName: "BS. Nguyễn Công Toại",
    appointmentDate: "01/08/2026",
    appointmentTime: "13:30 - 14:00",
    reason: "Đau khớp gối",
    queueNumber: 2,
    status: "Waiting",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Đợi gọi số",
  },
  {
    id: 6,
    patientName: "Nguyễn Thị Lan",
    doctorName: "BS. Võ Thanh Bình",
    appointmentDate: "01/08/2026",
    appointmentTime: "08:00 - 08:30",
    reason: "Khám tim mạch",
    queueNumber: 1,
    status: "Waiting",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Đã đến bệnh viện",
  },
  {
    id: 7,
    patientName: "Hoàng Gia Huy",
    doctorName: "BS. Nguyễn Công Toại",
    appointmentDate: "01/08/2026",
    appointmentTime: "14:00 - 14:30",
    reason: "Khó thở",
    queueNumber: 3,
    status: "InProgress",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Bác sĩ đang khám",
  },
  {
    id: 8,
    patientName: "Đặng Thanh Hà",
    doctorName: "BS. Võ Thanh Bình",
    appointmentDate: "01/08/2026",
    appointmentTime: "08:30 - 09:00",
    reason: "Tăng huyết áp",
    queueNumber: 2,
    status: "InProgress",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Đang đo huyết áp",
  },
  {
    id: 9,
    patientName: "Lý Quốc Bảo",
    doctorName: "BS. Trần Minh Tuấn",
    appointmentDate: "01/08/2026",
    appointmentTime: "09:30 - 10:00",
    reason: "Đau bụng",
    queueNumber: 4,
    status: "InProgress",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Đang siêu âm",
  },
  {
    id: 10,
    patientName: "Bùi Ngọc Ánh",
    doctorName: "BS. Trần Minh Tuấn",
    appointmentDate: "01/08/2026",
    appointmentTime: "10:00 - 10:30",
    reason: "Khám sức khỏe định kỳ",
    queueNumber: 5,
    status: "Completed",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Đã kê đơn thuốc",
  },
  {
    id: 11,
    patientName: "Nguyễn Văn An (Con)",
    doctorName: "BS. Nguyễn Công Toại",
    appointmentDate: "01/08/2026",
    appointmentTime: "15:00 - 15:30",
    reason: "Khám cho con bị sốt",
    queueNumber: 5,
    status: "Completed",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Đã hoàn thành khám",
  },
  {
    id: 12,
    patientName: "Lê Thị Hoa",
    doctorName: "BS. Võ Thanh Bình",
    appointmentDate: "01/08/2026",
    appointmentTime: "09:00 - 09:30",
    reason: "Dị ứng da",
    queueNumber: 3,
    status: "Completed",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Đã cấp thuốc",
  },
  {
    id: 13,
    patientName: "Phạm Văn Nam",
    doctorName: "BS. Nguyễn Công Toại",
    appointmentDate: "01/08/2026",
    appointmentTime: "15:30 - 16:00",
    reason: "Đau vai gáy",
    queueNumber: 6,
    status: "Cancelled",
    cancelReason: "Bệnh nhân bận việc",
    cancelTime: "01/08/2026 08:10",
    cancelledBy: "Lễ tân",
    notes: "Lễ tân đã xác nhận hủy lịch",
  },
  {
    id: 14,
    patientName: "Trần Thị Mai",
    doctorName: "BS. Võ Thanh Bình",
    appointmentDate: "01/08/2026",
    appointmentTime: "09:30 - 10:00",
    reason: "Khám mắt",
    queueNumber: 4,
    status: "Cancelled",
    cancelReason: "Bác sĩ nghỉ đột xuất",
    cancelTime: "01/08/2026 13:20",
    cancelledBy: "Lễ tân",
    notes: "Lễ tân thông báo đổi lịch",
  },
  {
    id: 15,
    patientName: "Võ Minh Đức",
    doctorName: "BS. Trần Minh Tuấn",
    appointmentDate: "01/08/2026",
    appointmentTime: "10:30 - 11:00",
    reason: "Khám tai mũi họng",
    queueNumber: 6,
    status: "Cancelled",
    cancelReason: "Không liên hệ được bệnh nhân",
    cancelTime: "01/08/2026 09:30",
    cancelledBy: "Lễ tân",
    notes: "Lễ tân hủy lịch",
  },
  {
    id: 16,
    patientName: "Nguyễn Thị Lan",
    doctorName: "BS. Nguyễn Công Toại",
    appointmentDate: "01/08/2026",
    appointmentTime: "16:00 - 16:30",
    reason: "Khám đau lưng",
    queueNumber: 7,
    status: "NoShow",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Bệnh nhân không đến",
  },
  {
    id: 17,
    patientName: "Hoàng Gia Huy",
    doctorName: "BS. Võ Thanh Bình",
    appointmentDate: "01/08/2026",
    appointmentTime: "11:00 - 11:30",
    reason: "Khám tiểu đường",
    queueNumber: 7,
    status: "NoShow",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Quá giờ hẹn",
  },
  {
    id: 18,
    patientName: "Đặng Thanh Hà (Mẹ)",
    doctorName: "BS. Võ Thanh Bình",
    appointmentDate: "01/08/2026",
    appointmentTime: "11:30 - 12:00",
    reason: "Khám cho mẹ",
    queueNumber: 8,
    status: "NoShow",
    cancelReason: null,
    cancelTime: null,
    cancelledBy: null,
    notes: "Không có mặt tại phòng khám",
  },
];
