import type { Medicine, MedicineCategory } from "./types";

export const medicineCategories: MedicineCategory[] = [
  { categoryId: 1, categoryName: "Giảm đau - Hạ sốt" },
  { categoryId: 2, categoryName: "Kháng sinh" },
  { categoryId: 3, categoryName: "Vitamin" },
  { categoryId: 4, categoryName: "Tiêu hóa" },
  { categoryId: 5, categoryName: "Hô hấp" },
  { categoryId: 6, categoryName: "Tim mạch" },
  { categoryId: 7, categoryName: "Dị ứng" },
  { categoryId: 8, categoryName: "Tiểu đường" },
  { categoryId: 9, categoryName: "Sát khuẩn" },
  { categoryId: 10, categoryName: "Khác" },
];

export const initialMedicines: Medicine[] = [
  // Giảm đau - Hạ sốt
  {
    medicineId: 1,
    categoryId: 1,
    medicineName: "Paracetamol 500mg",
    unit: "Viên",
    description: "Thuốc giảm đau, hạ sốt",
    defaultUsage: "Uống 1 viên khi sốt hoặc đau",
    unitPrice: 2000,
    stockQuantity: 5000,
    expiryDate: "2028-12-31",
    status: "Đang hoạt động",
  },
  {
    medicineId: 2,
    categoryId: 1,
    medicineName: "Ibuprofen 400mg",
    unit: "Viên",
    description: "Thuốc giảm đau, kháng viêm",
    defaultUsage: "Uống sau bữa ăn",
    unitPrice: 5000,
    stockQuantity: 3000,
    expiryDate: "2028-09-30",
    status: "Đang hoạt động",
  },
  // Kháng sinh
  {
    medicineId: 3,
    categoryId: 2,
    medicineName: "Amoxicillin 500mg",
    unit: "Viên",
    description: "Kháng sinh Penicillin",
    defaultUsage: "Uống theo chỉ định bác sĩ",
    unitPrice: 6000,
    stockQuantity: 2500,
    expiryDate: "2028-10-20",
    status: "Đang hoạt động",
  },
  {
    medicineId: 4,
    categoryId: 2,
    medicineName: "Azithromycin 500mg",
    unit: "Viên",
    description: "Kháng sinh phổ rộng",
    defaultUsage: "Uống 1 viên/ngày",
    unitPrice: 18000,
    stockQuantity: 1200,
    expiryDate: "2028-08-25",
    status: "Đang hoạt động",
  },
  {
    medicineId: 5,
    categoryId: 2,
    medicineName: "Cefixime 200mg",
    unit: "Viên",
    description: "Kháng sinh Cephalosporin",
    defaultUsage: "Uống theo toa",
    unitPrice: 15000,
    stockQuantity: 1000,
    expiryDate: "2028-11-15",
    status: "Đang hoạt động",
  },
  // Vitamin
  {
    medicineId: 6,
    categoryId: 3,
    medicineName: "Vitamin C 500mg",
    unit: "Viên",
    description: "Bổ sung Vitamin C",
    defaultUsage: "Uống sau ăn",
    unitPrice: 3000,
    stockQuantity: 4000,
    expiryDate: "2029-01-15",
    status: "Đang hoạt động",
  },
  {
    medicineId: 7,
    categoryId: 3,
    medicineName: "Vitamin B Complex",
    unit: "Viên",
    description: "Bổ sung Vitamin nhóm B",
    defaultUsage: "Uống 1 viên/ngày",
    unitPrice: 4000,
    stockQuantity: 2500,
    expiryDate: "2028-12-20",
    status: "Đang hoạt động",
  },
  // Tiêu hóa
  {
    medicineId: 8,
    categoryId: 4,
    medicineName: "Omeprazole 20mg",
    unit: "Viên",
    description: "Điều trị viêm loét dạ dày",
    defaultUsage: "Uống trước bữa sáng",
    unitPrice: 7000,
    stockQuantity: 1800,
    expiryDate: "2028-07-30",
    status: "Đang hoạt động",
  },
  {
    medicineId: 9,
    categoryId: 4,
    medicineName: "Smecta",
    unit: "Gói",
    description: "Điều trị tiêu chảy",
    defaultUsage: "Pha với nước trước khi uống",
    unitPrice: 6000,
    stockQuantity: 1000,
    expiryDate: "2028-09-18",
    status: "Đang hoạt động",
  },
  // Hô hấp
  {
    medicineId: 10,
    categoryId: 5,
    medicineName: "Acetylcysteine 200mg",
    unit: "Gói",
    description: "Thuốc long đờm",
    defaultUsage: "Pha với nước",
    unitPrice: 8000,
    stockQuantity: 1500,
    expiryDate: "2028-10-05",
    status: "Đang hoạt động",
  },
  {
    medicineId: 11,
    categoryId: 5,
    medicineName: "Salbutamol 2mg",
    unit: "Viên",
    description: "Thuốc giãn phế quản",
    defaultUsage: "Uống theo chỉ định",
    unitPrice: 5000,
    stockQuantity: 1200,
    expiryDate: "2028-11-30",
    status: "Đang hoạt động",
  },
  // Tim mạch
  {
    medicineId: 12,
    categoryId: 6,
    medicineName: "Amlodipine 5mg",
    unit: "Viên",
    description: "Điều trị tăng huyết áp",
    defaultUsage: "Uống 1 viên mỗi sáng",
    unitPrice: 8000,
    stockQuantity: 2000,
    expiryDate: "2028-12-31",
    status: "Đang hoạt động",
  },
  {
    medicineId: 13,
    categoryId: 6,
    medicineName: "Atorvastatin 20mg",
    unit: "Viên",
    description: "Điều trị mỡ máu",
    defaultUsage: "Uống vào buổi tối",
    unitPrice: 15000,
    stockQuantity: 1500,
    expiryDate: "2029-02-28",
    status: "Đang hoạt động",
  },
  // Dị ứng
  {
    medicineId: 14,
    categoryId: 7,
    medicineName: "Cetirizine 10mg",
    unit: "Viên",
    description: "Thuốc chống dị ứng",
    defaultUsage: "Uống 1 viên buổi tối",
    unitPrice: 4000,
    stockQuantity: 2200,
    expiryDate: "2028-09-15",
    status: "Đang hoạt động",
  },
  {
    medicineId: 15,
    categoryId: 7,
    medicineName: "Loratadine 10mg",
    unit: "Viên",
    description: "Thuốc chống dị ứng",
    defaultUsage: "Uống 1 viên/ngày",
    unitPrice: 5000,
    stockQuantity: 1800,
    expiryDate: "2028-10-31",
    status: "Đang hoạt động",
  },
  // Tiểu đường
  {
    medicineId: 16,
    categoryId: 8,
    medicineName: "Metformin 500mg",
    unit: "Viên",
    description: "Điều trị đái tháo đường",
    defaultUsage: "Uống sau bữa ăn",
    unitPrice: 4500,
    stockQuantity: 2500,
    expiryDate: "2028-12-10",
    status: "Đang hoạt động",
  },
  {
    medicineId: 17,
    categoryId: 8,
    medicineName: "Gliclazide 30mg",
    unit: "Viên",
    description: "Điều trị đái tháo đường",
    defaultUsage: "Uống trước bữa sáng",
    unitPrice: 7000,
    stockQuantity: 1200,
    expiryDate: "2028-11-20",
    status: "Đang hoạt động",
  },
  // Sát khuẩn
  {
    medicineId: 18,
    categoryId: 9,
    medicineName: "Povidone Iodine 10%",
    unit: "Chai",
    description: "Dung dịch sát khuẩn",
    defaultUsage: "Dùng ngoài da",
    unitPrice: 45000,
    stockQuantity: 300,
    expiryDate: "2029-03-31",
    status: "Đang hoạt động",
  },
  {
    medicineId: 19,
    categoryId: 9,
    medicineName: "Nước muối sinh lý 0.9%",
    unit: "Chai",
    description: "Dung dịch vệ sinh",
    defaultUsage: "Dùng theo hướng dẫn",
    unitPrice: 15000,
    stockQuantity: 800,
    expiryDate: "2029-01-31",
    status: "Đang hoạt động",
  },
  // Khác
  {
    medicineId: 20,
    categoryId: 10,
    medicineName: "Dung dịch Oresol",
    unit: "Gói",
    description: "Bù nước và điện giải",
    defaultUsage: "Pha đúng hướng dẫn",
    unitPrice: 8000,
    stockQuantity: 900,
    expiryDate: "2028-08-31",
    status: "Đang hoạt động",
  },
];
