import type { Notification } from "./types";

export const initialNotifications: Notification[] = [
  {
    notificationId: 1,
    userId: "usr-admin-01",
    title: "Lịch hẹn mới đã được đặt",
    content: "Nguyễn Văn An đã đặt lịch hẹn với bác sĩ Nguyễn Văn Bình vào ngày 20/06/2026 lúc 08:00.",
    type: "APPOINTMENT_NEW",
    relatedId: 101,
    relatedType: "APPOINTMENT",
    isRead: false,
    readAt: null,
    createdAt: "2 phút trước",
  },
  {
    notificationId: 2,
    userId: "usr-admin-01",
    title: "Cuộc hẹn đã bị hủy",
    content: "Phạm Thị Dũng đã hủy lịch hẹn với bác sĩ Nguyễn Văn Bình vào ngày 20/06/2026.",
    type: "APPOINTMENT_CANCELLED",
    relatedId: 102,
    relatedType: "APPOINTMENT",
    isRead: false,
    readAt: null,
    createdAt: "15 phút trước",
  },
  {
    notificationId: 3,
    userId: "usr-admin-01",
    title: "Cuộc hẹn đã hoàn tất",
    content: "Lê Văn Cường đã hoàn tất cuộc hẹn khám bệnh với bác sĩ Lê Văn Phúc. Đơn thuốc đã được cấp.",
    type: "APPOINTMENT_COMPLETED",
    relatedId: 103,
    relatedType: "APPOINTMENT",
    isRead: true,
    readAt: "2026-07-31T15:30:00Z",
    createdAt: "1 giờ trước",
  },
  {
    notificationId: 4,
    userId: "usr-admin-01",
    title: "Bệnh nhân mới đăng ký",
    content: "Bùi Thị Hoa đã được đăng ký là bệnh nhân mới trong hệ thống.",
    type: "PATIENT_REGISTERED",
    relatedId: 401,
    relatedType: "PATIENT",
    isRead: true,
    readAt: "2026-07-31T14:30:00Z",
    createdAt: "2 giờ trước",
  },
  {
    notificationId: 5,
    userId: "usr-admin-01",
    title: "Lời nhắc cuộc hẹn",
    content: "Nhắc nhở: Hoàng Văn Em có hẹn khám với bác sĩ Trần Thị Lan vào ngày mai lúc 10:00.",
    type: "APPOINTMENT_REMINDER",
    relatedId: 105,
    relatedType: "APPOINTMENT",
    isRead: true,
    readAt: "2026-07-31T13:30:00Z",
    createdAt: "3 giờ trước",
  },
  {
    notificationId: 6,
    userId: "usr-admin-01",
    title: "Lịch hẹn mới đã được đặt",
    content: "Trần Thị Bình đã đặt lịch hẹn với bác sĩ Trần Thị Lan vào ngày 21/06/2026 lúc 14:00.",
    type: "APPOINTMENT_NEW",
    relatedId: 106,
    relatedType: "APPOINTMENT",
    isRead: true,
    readAt: "2026-07-31T11:30:00Z",
    createdAt: "5 giờ trước",
  },
  {
    notificationId: 7,
    userId: "usr-admin-01",
    title: "Cuộc hẹn đã hoàn tất",
    content: "Võ Thị Giang đã hoàn tất cuộc hẹn khám bệnh với bác sĩ Trần Thị Lan.",
    type: "APPOINTMENT_COMPLETED",
    relatedId: 107,
    relatedType: "APPOINTMENT",
    isRead: true,
    readAt: "2026-07-30T16:00:00Z",
    createdAt: "1 ngày trước",
  },
  {
    notificationId: 8,
    userId: "usr-admin-01",
    title: "Bệnh nhân mới đăng ký",
    content: "Đặng Văn Kiên đã được đăng ký là bệnh nhân mới trong hệ thống.",
    type: "PATIENT_REGISTERED",
    relatedId: 402,
    relatedType: "PATIENT",
    isRead: true,
    readAt: "2026-07-29T10:00:00Z",
    createdAt: "2 ngày trước",
  },
];
